CREATE TABLE [dbo].[Npcs]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Type] INT NOT NULL, 
    [Name] NVARCHAR(20) NOT NULL, 
    [Status] INT NOT NULL, 
    [Mode] INT NOT NULL DEFAULT 0, 
    [Race] INT NOT NULL DEFAULT 0
)
